config:
  argocd:
    grpcWeb: true
    serverAddress: https://argocd-server.argocd.svc.cluster.local
    insecure: true
  gitCommitUser: obleey
  gitCommitEmail: miha.oblishar@gmail.com
  registries:
    - name: LinuxServer
      prefix: lscr.io
      api_url: https://lscr.io
      ping: true
      insecure: false
      defaultns: linuxserver
