config:
  argocd:
    grpcWeb: true
    serverAddress: https://argocd-server.argocd.svc.cluster.local
    insecure: true
  gitCommitUser: obleey
  gitCommitEmail: your@email.com
  registries:
    - name: lscr.io
      prefix: lscr.io
      ping: true
      insecure: false

authScripts:
  enabled: false
