apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: sonarr
  namespace: argocd
spec:
  applicationRefs:
    - name: sonarr
      namespace: argocd
  images:
    - image: lscr.io/linuxserver/sonarr
      strategy: latest
      writeBack:
        method: git
        git:
          branch: main
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: prowlarr
  namespace: argocd
spec:
  applicationRefs:
    - name: prowlarr
      namespace: argocd
  images:
    - image: lscr.io/linuxserver/prowlarr
      strategy: latest
      writeBack:
        method: git
        git:
          branch: main
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: jellyfin
  namespace: argocd
spec:
  applicationRefs:
    - name: jellyfin
      namespace: argocd
  images:
    - image: lscr.io/linuxserver/jellyfin
      strategy: latest
      writeBack:
        method: git
        git:
          branch: main
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  applicationRefs:
    - name: qbittorrent
      namespace: argocd
  images:
    - image: lscr.io/linuxserver/qbittorrent
      strategy: latest
      writeBack:
        method: git
        git:
          branch: main
