apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: servarr-apps
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: latest
  writeBackConfig:
    method: git
    git:
      branch: main
  applicationRefs:
    - namePattern: sonarr
      images:
        - image: lscr.io/linuxserver/sonarr
    - namePattern: prowlarr
      images:
        - image: lscr.io/linuxserver/prowlarr
    - namePattern: jellyfin
      images:
        - image: lscr.io/linuxserver/jellyfin
    - namePattern: qbittorrent
      images:
        - image: lscr.io/linuxserver/qbittorrent
