config:
  argocd:
    grpcWeb: true
    serverAddress: https://argocd-server.argocd.svc.cluster.local
    insecure: true

credentials:
  - registry: lscr.io
    username: anonymous
    passwordSecret:
      name: ""
      key: ""
