---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBA/7QaRgD5qN64pBMvxEIDxxuvnbcTIpyn3DUIxvCuZ8gXXPdQVfwIprnrHd+uEbv/wPXrayuU4FiQG+CGIwD3tucDI0aQcsfmynhbDfBs5dkV4ZiZbVts/PPslwwpEsrxO23rm6e1cbZx2+dpSevm7DmEQe2pLBkrJkLih9cZyLSr7KwksW80YAf2PkwK+w3gf8brTpM/ep4WzcVoLsLz4FUyw1HlAJONNTKPmRxrcZxR8GZoEIxul7c8t3LpCODjtmsjgEOBjQHQreVl6jIuOo6y4QCjUO8GGKMkgZXptzyYhOtrDUAh4s6JNHRrHEAZDwTEwUr26P8MsuikOiRxa7OcNoEbTadk3cm/ZWhBcmbGjxCBBNsopjAHDHNfn9DndX8pNiz9bLk+BbylvKz9+Gcmv66Dq6EQfMk3dadVbbUE/CvGODSRCMUPVO8BxgrwU3GTVX0x5Ptnp/06fphly5oU7tL/SM05fuOx5hwn1UT+/R7p2KDIWA6FB4FZPDYJgh/cd8gbw03jAM7jQ6yW+GDNXCZhv8zQz2e+lXQ7TC3kklaMuzCxqDDjWFUhgSC1n+2CPWoCslxthS8a8nhMy5cdVo9FYrOQYFFhi8FW78Xn1zlC93UAVHBHyu2YEmPpaIK02nde8xTQltm6FqaLSYf9/tHltqxpK4tvEreAckzFM7RdjPjC9RWZIlJ6WuyruGg84T7qynxS8cmXC4MiPs71JHZpT1wSymQw6b6IIb1rA9NQd6G/Y/ytm16g20wIZPtu0yMm69a+Ug==
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
