---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgASVYyi4bU4pA50Ox4EFBVnlxe4kTdNCH0IPyMci9c5Yzs950jpzkRytHxfTBTrQSUEgRAfLdVCC9qvL00kH8ulK8YKCUhcLah9JfzhxogUH4/Cy4Bc+AdsqZRMRhTNavotrgoAZYpURaSjaxQ1YqfougNA+pkCceEbO8iAbpuTPPCfk13625jVvBE2om+y2+fgOXbxdDmQeqruIQtYlFv22MfglG3SuzAd1apemBXcF7plWMIu77DSVP55Ftfadvw/7gC2pAfgHA748bBu9+sK62KhEbeXS/yfvicsdOAtOneoiNdNI5ag98eBAvLg997MoeETc4w2sWi7Ap7+6EnESKPGEru373XzFfIb7iHUAc4rcot6+LkS3TrIWSoIu3REvsq03grFbAGaUAIgn2bnAlJm7TF7OiKwz7lq1wWzPuOchzCpy9vP6SOn4O8NOVCnIxI/dajUPPy4wXa2h3bHJG72N/hZWMEXejKsiU2fRdxh3Gey+PFNxLyi+UdkFxM8imzm2taB17c1bWw7kGrHjDJm0Nwo96ZfKneKctWb4x+FmsrcQfyN7q1DD+CGBthUsKQd9FZOPozm7Sok6B8Rssjuu6NJ2i/ai96j4CgYD3XX/ZRK5Stoh9PFawIDYRad3y19LlrNWNDSzdVjjhhd7dqeaxMjSud4quTJxuOxQMCu7Bm3rw5jIxctPpUlX+WEDsvqCY1otfVxL8uvSsz7ISJ8BrEq5087yaVc3c9Xk1f8I9DEjvNj
    username: AgAIt09Pmx07LY1HbA8SJUi465kzhxFj8pj3mdzGmt3vFqzVaxaRaQayd4SN2Ye/hLqpzARafS2w+EgkDN4kwsoxOAEVXhceTGcDUBoyWsTJBMs3OnjBRg9mF31gVdUDvmyqqbg0JEzQMgN7b7K+Z4UiNGL5RSr5BphLy4rMpd5KFyH3Z+BYqv2lK+ikTb1cOgpUoe/Q3EVfH5f+s3NJjUscBoDFBqqjVlutAuCPBLvogOAp9sBik6JPM1umQhOzcDI7yOk9UA8OEtjQ5aPgQidsq5BwPG+5AlnIscyv0qymz2IMkFNaTS6DnmZiPs0Ymx7PZGQwki5fTkMICu1lMXMo8N76IvU9nX3/snpQgD+CNv2CLjJUyViqewPD5YGIeTNERSvSapms1XPU6NIeVpO7PxQc3axAaDyWDgm7IDLzZ3j48PUlpUZ/CwcNtrj2jcopZRmQXdFjf0HQZB+AJTVWyI/bEpSEf3MKN310TbyAvbUHfKK32cwsqGxLXMXoFSfbPHSfP2XDayqWA8iEAeOGoiuB0mJFr2rprHgKT2Xbij53vuorf6bro8DKVYmxmNsnohVpMYvH8rXSeUW4XBHMAmgfR8cIaFa7bxFi4qyg+Kqs2cyUlQ9hdcWnosmnHujalwUExF38/vUInSI6uT/iswgEVWQlMopTrQA6SOaD+IuyUc3fQZDXFjyqIft3GylESVrxASg=
  template:
    metadata:
      name: git-creds
      namespace: argocd
