apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-data
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
