apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: prowlarr=lscr.io/linuxserver/prowlarr
    argocd-image-updater.argoproj.io/prowlarr.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/obleey/kube-homelab
    targetRevision: HEAD
    path: deployments/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: servarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
