apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "#deployments"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "#deployments"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "#deployments"
spec:
  project: default
  source:
    repoURL: https://github.com/obleey/kube-homelab
    targetRevision: HEAD
    path: deployments/qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: servarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
