apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
  namespace: servarr
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Ljubljana"
  VERSION: "docker"
  ADVERTISE_IP: "http://10.0.0.101:32400"
