apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
