---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-secret
  namespace: servarr
spec:
  encryptedData:
    PLEX_CLAIM: AgBxrAQ1AOJL2oSvL2cNZhs1m2QMB98khPEc1ECLmqlInCiF4HFfBFIawIamGP9X2GTp19gHsb4vHHgM02BEdhXaLFPcfXHB+mIgMh+isjW/30vDKVlzMvb1gTY47Du/1nl7h+xOrk/agdj8yxvltibxFrNMx0327Ye3PhirgO7tSkg/fJ2ZIE9L1iTrGaYpweMwuUTTOHWFoF/4gbbaNGUA43VacgrMH37w0dhHjIyOQFeci9ZP/RNsmGltOx9kY9To75d9LS6u/2Grx8TsyWD0EggmURYXZVMpdD11xwy/jeSsvhN2s8ie2pnMf3uR/KvQQSQJvbpQv2RliaFbx0/IWpvcOuSs3CLDtkD8RvYGdnzH9awoZaTFN/AfTH92CXcg8jxFXCeQ2qJy07e+lepVetbAciWlNplcJ7wXHrbKgzA4/rliBrm+JrpWQ5ZbaijOaYFFfPtYSIWxf5B23njOHwPe57BveqRD8cWnsgKBg4Ag8gJL8KcFXjvD6f2iJts0V82Fsp7eXfRjrCxphFzcE+P+F1vE7xkpsD99I9aUaqH2lA/yIeoNUId8ewmtyqx8fkDYTUrQByAZARhkliA57O1mHsOfsG+Czq7xEr9jeiyRDtBddIt/QQFg9bLzBPBnPsmCPlebogqBiXAPE43nkwOxi3Hi4WkC7mteG8z0pnmd4hhPaPJTAxEkt7H0gfDqx737JNf7tMyGLHOo1agcIa7iUAZgBnzmyQ==
  template:
    metadata:
      name: plex-secret
      namespace: servarr
    type: Opaque
