---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-secret
  namespace: servarr
spec:
  encryptedData:
    PLEX_CLAIM: AgAz8pnxi1gPzw3Lt6IHmShrQWgZ0js471Wjm10+mFdwEkZ9JtvIFFDklr7A5H77+vxXcpOCxbejCbhRVIKS8oFwgJeGDVcplsxS8qNM8BfabdPxzd5ta//uSQhmupW5YMGiXdhKRR3wA70sTAa3ixU+YqijYTAwo/TgHHU5QkBRaEVuqfN/1Gd6RVsX19hu+7zx3j8/TErqJdYnDrqYqKNj3/r8iuE8vbcVtuLnjE4oTWTFhf+PwHz+opHGzqS2FjqR9SpVVwlxdB9O8s/NScTjHMz9Q23hD+nFXPISV/H4cew2ZokgTUulAB1kfJHTVbVtJsWdNguSD6W2Wq9JV/UBxWM72pB8tAxrpxOxOcNWo+f4gOq5H7BGzWQTm/7RRakPWjt9m1mPirJfVUjqER1XcJOU+L5dKLWGJC5UK0FxIZ061ZaMTH/P7kSlIvuG1C/TF0tr74iOJGu/w30OiPpN1gXlUANg+DJPtf2apmvc1VNDouEuKmU/QqSO6myDYMymnnG7QqHDgWMHLuAo0imc7NtJ9c8Cm04Lp7q6mDxPTsiMyeZU5CeQbHwNzUMPX5b1nUITeEJF/+b/1U+AZut83hIT7pm7n84f4nKkZTnbH/wainHwfs6ODB9ZCWMhg+4gzVgWUd2/QlC4kPBu+iAb39oIxi/btaE0pWxDvALXcOHCCL2Pkb/FacXMlzc9cE1gCDlFKELPuArdgWA/AbmMayHHNj+VELZWqA==
  template:
    metadata:
      name: plex-secret
      namespace: servarr
