apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
